spec:  
  template:
    metadata:
      annotations:
        fabric8.io/git-branch: todo-migrate
        fabric8.io/git-commit: 20d773370efdfce3221f56348ba2c544558a58a3
        fabric8.io/git-url: https://github.com/siggy81/DO288-apps
      creationTimestamp: null
      labels:
        app: todo-api
        group: com.redhat.training.example
        provider: fabric8
        version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: db-config
        image: image-registry.openshift-image-registry.svc:5000/luca-mercuri-hummerhr-it-todo-migrate/todo-api@sha256:1e2f2e55651c2f5451344140cf3135ee272ea4a147db32c385a5703bbaeffee0
        imagePullPolicy: IfNotPresent
        name: thorntail-v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - thorntail-v2
      from:
        kind: ImageStreamTag
        name: todo-api:latest
        namespace: luca-mercuri-hummerhr-it-todo-migrate
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/luca-mercuri-hummerhr-it-todo-migrate/todo-api@sha256:1e2f2e55651c2f5451344140cf3135ee272ea4a147db32c385a5703bbaeffee0
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-12-18T10:17:06Z"
    lastUpdateTime: "2020-12-18T10:17:06Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2020-12-18T10:17:06Z"
    lastUpdateTime: "2020-12-18T10:17:09Z"
    message: replication controller "todo-api-2" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 2
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
